x-common:
  user: &user "101:101"
  clickhouse:
    image: &ch_image "clickhouse/clickhouse-server:25.12.1.649-alpine"
    depends_on: &depends_on
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  keeper:
    image: &keeper_image "clickhouse/clickhouse-keeper:25.12.1.649-alpine"

services:
  clickhouse-01:
    image: *ch_image
    user: *user
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on: *depends_on
  clickhouse-02:
    image: *ch_image
    user: *user
    container_name: clickhouse-02
    hostname: clickhouse-02
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8124:8123"
      - "9001:9000"
    depends_on: *depends_on
  clickhouse-03:
    image: *ch_image
    user: *user
    container_name: clickhouse-03
    hostname: clickhouse-03
    volumes:
      - ${PWD}/fs/volumes/clickhouse-03/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-03/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8125:8123"
      - "9002:9000"
    depends_on: *depends_on
  clickhouse-04:
    image: *ch_image
    user: *user
    container_name: clickhouse-04
    hostname: clickhouse-04
    volumes:
      - ${PWD}/fs/volumes/clickhouse-04/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-04/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8126:8123"
      - "9003:9000"
    depends_on: *depends_on

  clickhouse-05:
    image: *ch_image
    user: *user
    container_name: clickhouse-05
    hostname: clickhouse-05
    volumes:
      - ${PWD}/fs/volumes/clickhouse-05/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-05/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8127:8123"
      - "9004:9000"
    depends_on: *depends_on

  clickhouse-06:
    image: *ch_image
    user: *user
    container_name: clickhouse-06
    hostname: clickhouse-06
    volumes:
      - ${PWD}/fs/volumes/clickhouse-06/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-06/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8128:8123"
      - "9005:9000"
    depends_on: *depends_on

  clickhouse-keeper-01:
    image: *keeper_image
    user: *user
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "127.0.0.1:9181:9181"

  clickhouse-keeper-02:
    image: *keeper_image
    user: *user
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "127.0.0.1:9182:9181"

  clickhouse-keeper-03:
    image: *keeper_image
    user: *user
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "127.0.0.1:9183:9181"
